

# git include
include ../boilerplate/help.mk
include ../boilerplate/os.mk
include ../boilerplate/gitr.mk

include ../boilerplate/flu.mk
include ../boilerplate/srv.mk
include ../boilerplate/lang.mk

# hard override. Can also suck in exported environment variables
override FLU_SAMPLE_NAME=client


## Print all settings
print: ## print

	$(MAKE) os-print
	
	$(MAKE) gitr-print
	
	$(MAKE) flu-print

	$(MAKE) lang-print

	$(MAKE) srv-print

## So high
high: ## high
	@echo i wanna get...
