export GCP_PROJECT=?
export GCP_USER?

MINIO_ACCESSKEY="REPLACE_THIS"
MINIO_SECRETKEY="REPLACE_THIS"
MINIO_LOCATION="REPLACE_THIS"
MINIO_TIMEOUT="REPLACE_THIS"
MINIO_ENCKEY="REPLACE_THIS"

export MINIO_ACCESSKEY MINIO_SECRETKEY MINIO_LOCATION MINIO_TIMEOUT MINIO_ENCKEY
