package main

// DO NOT EDIT, this file is generated by hover at compile-time for the simple_ion plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	simple_ion "github.com/winwisely100/simple_ion/go"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&simple_ion.SimpleIonPlugin{}))
}
