# https://github.com/pingcap-incubator/tiup


# includes
BOILERPLATE_FSPATH=../../boilerplate

include $(BOILERPLATE_FSPATH)/core/help.mk
include $(BOILERPLATE_FSPATH)/core/gitu.mk
include $(BOILERPLATE_FSPATH)/core/go.mk

this-dep:
	go get github.com/pingcap-incubator/tiup
	