package internal

// Code generated by go generate using EMBED tool; DO NOT EDIT.

// const typedhello string = "Hello World"
const CONST_data_x_json string = "/data/x.json"
const CONST_data_x_sql string = "/data/x.sql"
const CONST_index_html string = "/index.html"
const CONST_lang_i18n_intl_messages_arb string = "/lang/i18n/intl_messages.arb"
const CONST_lang_i18n_lang_de_arb string = "/lang/i18n/lang_de.arb"
const CONST_lang_i18n_lang_de_json string = "/lang/i18n/lang_de.json"
const CONST_lang_i18n_lang_en_arb string = "/lang/i18n/lang_en.arb"
const CONST_lang_i18n_lang_en_json string = "/lang/i18n/lang_en.json"
const CONST_lang_i18n_lang_es_arb string = "/lang/i18n/lang_es.arb"
const CONST_lang_i18n_lang_es_json string = "/lang/i18n/lang_es.json"
const CONST_lang_i18n_lang_fr_arb string = "/lang/i18n/lang_fr.arb"
const CONST_lang_i18n_lang_fr_json string = "/lang/i18n/lang_fr.json"
const CONST_lang_i18n_lang_it_arb string = "/lang/i18n/lang_it.arb"
const CONST_lang_i18n_lang_it_json string = "/lang/i18n/lang_it.json"
const CONST_lang_i18n_lang_ur_arb string = "/lang/i18n/lang_ur.arb"
const CONST_lang_i18n_lang_ur_json string = "/lang/i18n/lang_ur.json"
