FROM golang:1.13

RUN GOPATH=`pwd` && go get -v -d github.com/pion/ion/...

WORKDIR /app

RUN go build -o ion ${GOPATH}/src/github.com/pion/ion/cmd/ion/main.go

RUN mkdir configs

RUN cp ${GOPATH}/src/github.com/pion/ion/configs/ion.toml ./configs

# generate key.pem and cert.pem using https://github.com/FiloSottile/mkcert 
COPY ./key.pem ./configs/

COPY ./cert.pem ./configs/

ENTRYPOINT ["./ion", "-c=./configs/ion.toml"]