FROM golang:1.13

RUN GOPATH=`pwd` && go get -v -d github.com/cloudwebrtc/ion/...

WORKDIR /app

RUN go build -o cloudwebrtc-islb ${GOPATH}/src/github.com/cloudwebrtc/ion/islb/main.go

RUN mkdir configs

RUN cp ${GOPATH}/src/github.com/cloudwebrtc/ion/conf/islb.toml ./configs

# generate key.pem and cert.pem using https://github.com/FiloSottile/mkcert 
COPY ./key.pem ./configs/

COPY ./cert.pem ./configs/

ENTRYPOINT ["./cloudwebrtc-islb", "-c=./configs/islb.toml"]