# https://github.com/hacker-dome/not_google_keep

# its uses NUID !

SAMPLE_FSPATH = not_google_keep

flu-desk-local-init: ## flu-desk-local-init
	cd $(SAMPLE_FSPATH) && hover init

flu-desk-local-run: ## flu-desk-local-run
	cd $(SAMPLE_FSPATH) && hover run

flu-web-run:
	cd $(SAMPLE_FSPATH) && flutter run -d chrome