// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListSupportRoleRequest struct {
	// optionally adds org_id to get all support roles
	// in that org.
	OrgId                string   `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSupportRoleRequest) Reset()         { *m = ListSupportRoleRequest{} }
func (m *ListSupportRoleRequest) String() string { return proto.CompactTextString(m) }
func (*ListSupportRoleRequest) ProtoMessage()    {}
func (*ListSupportRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ListSupportRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSupportRoleRequest.Unmarshal(m, b)
}
func (m *ListSupportRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSupportRoleRequest.Marshal(b, m, deterministic)
}
func (m *ListSupportRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSupportRoleRequest.Merge(m, src)
}
func (m *ListSupportRoleRequest) XXX_Size() int {
	return xxx_messageInfo_ListSupportRoleRequest.Size(m)
}
func (m *ListSupportRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSupportRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSupportRoleRequest proto.InternalMessageInfo

func (m *ListSupportRoleRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

type GetSupportRoleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSupportRoleRequest) Reset()         { *m = GetSupportRoleRequest{} }
func (m *GetSupportRoleRequest) String() string { return proto.CompactTextString(m) }
func (*GetSupportRoleRequest) ProtoMessage()    {}
func (*GetSupportRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetSupportRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSupportRoleRequest.Unmarshal(m, b)
}
func (m *GetSupportRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSupportRoleRequest.Marshal(b, m, deterministic)
}
func (m *GetSupportRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSupportRoleRequest.Merge(m, src)
}
func (m *GetSupportRoleRequest) XXX_Size() int {
	return xxx_messageInfo_GetSupportRoleRequest.Size(m)
}
func (m *GetSupportRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSupportRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSupportRoleRequest proto.InternalMessageInfo

func (m *GetSupportRoleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Orgs struct {
	Orgs                 []*Org   `protobuf:"bytes,1,rep,name=orgs,proto3" json:"orgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Orgs) Reset()         { *m = Orgs{} }
func (m *Orgs) String() string { return proto.CompactTextString(m) }
func (*Orgs) ProtoMessage()    {}
func (*Orgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Orgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orgs.Unmarshal(m, b)
}
func (m *Orgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orgs.Marshal(b, m, deterministic)
}
func (m *Orgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orgs.Merge(m, src)
}
func (m *Orgs) XXX_Size() int {
	return xxx_messageInfo_Orgs.Size(m)
}
func (m *Orgs) XXX_DiscardUnknown() {
	xxx_messageInfo_Orgs.DiscardUnknown(m)
}

var xxx_messageInfo_Orgs proto.InternalMessageInfo

func (m *Orgs) GetOrgs() []*Org {
	if m != nil {
		return m.Orgs
	}
	return nil
}

type ListOrgRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrgRequest) Reset()         { *m = ListOrgRequest{} }
func (m *ListOrgRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrgRequest) ProtoMessage()    {}
func (*ListOrgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ListOrgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrgRequest.Unmarshal(m, b)
}
func (m *ListOrgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrgRequest.Marshal(b, m, deterministic)
}
func (m *ListOrgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrgRequest.Merge(m, src)
}
func (m *ListOrgRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrgRequest.Size(m)
}
func (m *ListOrgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrgRequest proto.InternalMessageInfo

type GetOrgRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrgRequest) Reset()         { *m = GetOrgRequest{} }
func (m *GetOrgRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrgRequest) ProtoMessage()    {}
func (*GetOrgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *GetOrgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrgRequest.Unmarshal(m, b)
}
func (m *GetOrgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrgRequest.Marshal(b, m, deterministic)
}
func (m *GetOrgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrgRequest.Merge(m, src)
}
func (m *GetOrgRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrgRequest.Size(m)
}
func (m *GetOrgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrgRequest proto.InternalMessageInfo

func (m *GetOrgRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NewAnswerRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SelSupportRoleId     string   `protobuf:"bytes,2,opt,name=sel_support_role_id,json=selSupportRoleId,proto3" json:"sel_support_role_id,omitempty"`
	SelCampaignId        string   `protobuf:"bytes,3,opt,name=sel_campaign_id,json=selCampaignId,proto3" json:"sel_campaign_id,omitempty"`
	MinHoursPledged      string   `protobuf:"bytes,4,opt,name=min_hours_pledged,json=minHoursPledged,proto3" json:"min_hours_pledged,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAnswerRequest) Reset()         { *m = NewAnswerRequest{} }
func (m *NewAnswerRequest) String() string { return proto.CompactTextString(m) }
func (*NewAnswerRequest) ProtoMessage()    {}
func (*NewAnswerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *NewAnswerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAnswerRequest.Unmarshal(m, b)
}
func (m *NewAnswerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAnswerRequest.Marshal(b, m, deterministic)
}
func (m *NewAnswerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAnswerRequest.Merge(m, src)
}
func (m *NewAnswerRequest) XXX_Size() int {
	return xxx_messageInfo_NewAnswerRequest.Size(m)
}
func (m *NewAnswerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAnswerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewAnswerRequest proto.InternalMessageInfo

func (m *NewAnswerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewAnswerRequest) GetSelSupportRoleId() string {
	if m != nil {
		return m.SelSupportRoleId
	}
	return ""
}

func (m *NewAnswerRequest) GetSelCampaignId() string {
	if m != nil {
		return m.SelCampaignId
	}
	return ""
}

func (m *NewAnswerRequest) GetMinHoursPledged() string {
	if m != nil {
		return m.MinHoursPledged
	}
	return ""
}

type Answer struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// selected support role
	SelSupportRoleId string `protobuf:"bytes,2,opt,name=sel_support_role_id,json=selSupportRoleId,proto3" json:"sel_support_role_id,omitempty"`
	// selected campaign id
	SelCampaignId        string               `protobuf:"bytes,3,opt,name=sel_campaign_id,json=selCampaignId,proto3" json:"sel_campaign_id,omitempty"`
	MinHoursPledged      string               `protobuf:"bytes,4,opt,name=min_hours_pledged,json=minHoursPledged,proto3" json:"min_hours_pledged,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Answer) Reset()         { *m = Answer{} }
func (m *Answer) String() string { return proto.CompactTextString(m) }
func (*Answer) ProtoMessage()    {}
func (*Answer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *Answer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Answer.Unmarshal(m, b)
}
func (m *Answer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Answer.Marshal(b, m, deterministic)
}
func (m *Answer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Answer.Merge(m, src)
}
func (m *Answer) XXX_Size() int {
	return xxx_messageInfo_Answer.Size(m)
}
func (m *Answer) XXX_DiscardUnknown() {
	xxx_messageInfo_Answer.DiscardUnknown(m)
}

var xxx_messageInfo_Answer proto.InternalMessageInfo

func (m *Answer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Answer) GetSelSupportRoleId() string {
	if m != nil {
		return m.SelSupportRoleId
	}
	return ""
}

func (m *Answer) GetSelCampaignId() string {
	if m != nil {
		return m.SelCampaignId
	}
	return ""
}

func (m *Answer) GetMinHoursPledged() string {
	if m != nil {
		return m.MinHoursPledged
	}
	return ""
}

func (m *Answer) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Answers struct {
	Answers              []*Answer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Answers) Reset()         { *m = Answers{} }
func (m *Answers) String() string { return proto.CompactTextString(m) }
func (*Answers) ProtoMessage()    {}
func (*Answers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *Answers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Answers.Unmarshal(m, b)
}
func (m *Answers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Answers.Marshal(b, m, deterministic)
}
func (m *Answers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Answers.Merge(m, src)
}
func (m *Answers) XXX_Size() int {
	return xxx_messageInfo_Answers.Size(m)
}
func (m *Answers) XXX_DiscardUnknown() {
	xxx_messageInfo_Answers.DiscardUnknown(m)
}

var xxx_messageInfo_Answers proto.InternalMessageInfo

func (m *Answers) GetAnswers() []*Answer {
	if m != nil {
		return m.Answers
	}
	return nil
}

type SupportRole struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comment   string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Mandatory bool   `protobuf:"varint,4,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	Uom       string `protobuf:"bytes,5,opt,name=uom,proto3" json:"uom,omitempty"`
	MinHours  string `protobuf:"bytes,6,opt,name=min_hours,json=minHours,proto3" json:"min_hours,omitempty"`
	// org campaign id
	CampaignId           string               `protobuf:"bytes,7,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SupportRole) Reset()         { *m = SupportRole{} }
func (m *SupportRole) String() string { return proto.CompactTextString(m) }
func (*SupportRole) ProtoMessage()    {}
func (*SupportRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *SupportRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportRole.Unmarshal(m, b)
}
func (m *SupportRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportRole.Marshal(b, m, deterministic)
}
func (m *SupportRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportRole.Merge(m, src)
}
func (m *SupportRole) XXX_Size() int {
	return xxx_messageInfo_SupportRole.Size(m)
}
func (m *SupportRole) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportRole.DiscardUnknown(m)
}

var xxx_messageInfo_SupportRole proto.InternalMessageInfo

func (m *SupportRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SupportRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SupportRole) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *SupportRole) GetMandatory() bool {
	if m != nil {
		return m.Mandatory
	}
	return false
}

func (m *SupportRole) GetUom() string {
	if m != nil {
		return m.Uom
	}
	return ""
}

func (m *SupportRole) GetMinHours() string {
	if m != nil {
		return m.MinHours
	}
	return ""
}

func (m *SupportRole) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *SupportRole) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Org struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignName         string               `protobuf:"bytes,2,opt,name=campaign_name,json=campaignName,proto3" json:"campaign_name,omitempty"`
	LogoUrl              string               `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Goal                 string               `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	CrgQuantityMany      []string             `protobuf:"bytes,5,rep,name=crg_quantity_many,json=crgQuantityMany,proto3" json:"crg_quantity_many,omitempty"`
	CrgIdsMany           []string             `protobuf:"bytes,6,rep,name=crg_ids_many,json=crgIdsMany,proto3" json:"crg_ids_many,omitempty"`
	AlreadyPledged       string               `protobuf:"bytes,7,opt,name=already_pledged,json=alreadyPledged,proto3" json:"already_pledged,omitempty"`
	ActionTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=action_time,json=actionTime,proto3" json:"action_time,omitempty"`
	ActionLocation       string               `protobuf:"bytes,9,opt,name=action_location,json=actionLocation,proto3" json:"action_location,omitempty"`
	CampaignStill        string               `protobuf:"bytes,10,opt,name=campaign_still,json=campaignStill,proto3" json:"campaign_still,omitempty"`
	MinPioneers          string               `protobuf:"bytes,11,opt,name=min_pioneers,json=minPioneers,proto3" json:"min_pioneers,omitempty"`
	MinRebelsForMedia    string               `protobuf:"bytes,12,opt,name=min_rebels_for_media,json=minRebelsForMedia,proto3" json:"min_rebels_for_media,omitempty"`
	MinRebelsToWin       string               `protobuf:"bytes,13,opt,name=min_rebels_to_win,json=minRebelsToWin,proto3" json:"min_rebels_to_win,omitempty"`
	ActionLength         string               `protobuf:"bytes,14,opt,name=action_length,json=actionLength,proto3" json:"action_length,omitempty"`
	ActionType           string               `protobuf:"bytes,15,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	BackingOrg           []string             `protobuf:"bytes,16,rep,name=backing_org,json=backingOrg,proto3" json:"backing_org,omitempty"`
	Category             string               `protobuf:"bytes,17,opt,name=category,proto3" json:"category,omitempty"`
	Contact              string               `protobuf:"bytes,18,opt,name=contact,proto3" json:"contact,omitempty"`
	HistPrecedents       string               `protobuf:"bytes,19,opt,name=hist_precedents,json=histPrecedents,proto3" json:"hist_precedents,omitempty"`
	Organization         string               `protobuf:"bytes,20,opt,name=organization,proto3" json:"organization,omitempty"`
	Strategy             string               `protobuf:"bytes,21,opt,name=strategy,proto3" json:"strategy,omitempty"`
	VideoUrl             []string             `protobuf:"bytes,22,rep,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Uom                  string               `protobuf:"bytes,23,opt,name=uom,proto3" json:"uom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Org) Reset()         { *m = Org{} }
func (m *Org) String() string { return proto.CompactTextString(m) }
func (*Org) ProtoMessage()    {}
func (*Org) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *Org) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Org.Unmarshal(m, b)
}
func (m *Org) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Org.Marshal(b, m, deterministic)
}
func (m *Org) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Org.Merge(m, src)
}
func (m *Org) XXX_Size() int {
	return xxx_messageInfo_Org.Size(m)
}
func (m *Org) XXX_DiscardUnknown() {
	xxx_messageInfo_Org.DiscardUnknown(m)
}

var xxx_messageInfo_Org proto.InternalMessageInfo

func (m *Org) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Org) GetCampaignName() string {
	if m != nil {
		return m.CampaignName
	}
	return ""
}

func (m *Org) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *Org) GetGoal() string {
	if m != nil {
		return m.Goal
	}
	return ""
}

func (m *Org) GetCrgQuantityMany() []string {
	if m != nil {
		return m.CrgQuantityMany
	}
	return nil
}

func (m *Org) GetCrgIdsMany() []string {
	if m != nil {
		return m.CrgIdsMany
	}
	return nil
}

func (m *Org) GetAlreadyPledged() string {
	if m != nil {
		return m.AlreadyPledged
	}
	return ""
}

func (m *Org) GetActionTime() *timestamp.Timestamp {
	if m != nil {
		return m.ActionTime
	}
	return nil
}

func (m *Org) GetActionLocation() string {
	if m != nil {
		return m.ActionLocation
	}
	return ""
}

func (m *Org) GetCampaignStill() string {
	if m != nil {
		return m.CampaignStill
	}
	return ""
}

func (m *Org) GetMinPioneers() string {
	if m != nil {
		return m.MinPioneers
	}
	return ""
}

func (m *Org) GetMinRebelsForMedia() string {
	if m != nil {
		return m.MinRebelsForMedia
	}
	return ""
}

func (m *Org) GetMinRebelsToWin() string {
	if m != nil {
		return m.MinRebelsToWin
	}
	return ""
}

func (m *Org) GetActionLength() string {
	if m != nil {
		return m.ActionLength
	}
	return ""
}

func (m *Org) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

func (m *Org) GetBackingOrg() []string {
	if m != nil {
		return m.BackingOrg
	}
	return nil
}

func (m *Org) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Org) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *Org) GetHistPrecedents() string {
	if m != nil {
		return m.HistPrecedents
	}
	return ""
}

func (m *Org) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *Org) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *Org) GetVideoUrl() []string {
	if m != nil {
		return m.VideoUrl
	}
	return nil
}

func (m *Org) GetUom() string {
	if m != nil {
		return m.Uom
	}
	return ""
}

type NewAnswerResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAnswerResponse) Reset()         { *m = NewAnswerResponse{} }
func (m *NewAnswerResponse) String() string { return proto.CompactTextString(m) }
func (*NewAnswerResponse) ProtoMessage()    {}
func (*NewAnswerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *NewAnswerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAnswerResponse.Unmarshal(m, b)
}
func (m *NewAnswerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAnswerResponse.Marshal(b, m, deterministic)
}
func (m *NewAnswerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAnswerResponse.Merge(m, src)
}
func (m *NewAnswerResponse) XXX_Size() int {
	return xxx_messageInfo_NewAnswerResponse.Size(m)
}
func (m *NewAnswerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAnswerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewAnswerResponse proto.InternalMessageInfo

func (m *NewAnswerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *NewAnswerResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAnswerResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAnswerResponse) Reset()         { *m = DeleteAnswerResponse{} }
func (m *DeleteAnswerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAnswerResponse) ProtoMessage()    {}
func (*DeleteAnswerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *DeleteAnswerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAnswerResponse.Unmarshal(m, b)
}
func (m *DeleteAnswerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAnswerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAnswerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAnswerResponse.Merge(m, src)
}
func (m *DeleteAnswerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAnswerResponse.Size(m)
}
func (m *DeleteAnswerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAnswerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAnswerResponse proto.InternalMessageInfo

func (m *DeleteAnswerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AnswerIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerIdRequest) Reset()         { *m = AnswerIdRequest{} }
func (m *AnswerIdRequest) String() string { return proto.CompactTextString(m) }
func (*AnswerIdRequest) ProtoMessage()    {}
func (*AnswerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *AnswerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerIdRequest.Unmarshal(m, b)
}
func (m *AnswerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerIdRequest.Marshal(b, m, deterministic)
}
func (m *AnswerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerIdRequest.Merge(m, src)
}
func (m *AnswerIdRequest) XXX_Size() int {
	return xxx_messageInfo_AnswerIdRequest.Size(m)
}
func (m *AnswerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerIdRequest proto.InternalMessageInfo

func (m *AnswerIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SupportRoles struct {
	SupportRoles         []*SupportRole `protobuf:"bytes,1,rep,name=support_roles,json=supportRoles,proto3" json:"support_roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SupportRoles) Reset()         { *m = SupportRoles{} }
func (m *SupportRoles) String() string { return proto.CompactTextString(m) }
func (*SupportRoles) ProtoMessage()    {}
func (*SupportRoles) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *SupportRoles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportRoles.Unmarshal(m, b)
}
func (m *SupportRoles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportRoles.Marshal(b, m, deterministic)
}
func (m *SupportRoles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportRoles.Merge(m, src)
}
func (m *SupportRoles) XXX_Size() int {
	return xxx_messageInfo_SupportRoles.Size(m)
}
func (m *SupportRoles) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportRoles.DiscardUnknown(m)
}

var xxx_messageInfo_SupportRoles proto.InternalMessageInfo

func (m *SupportRoles) GetSupportRoles() []*SupportRole {
	if m != nil {
		return m.SupportRoles
	}
	return nil
}

func init() {
	proto.RegisterType((*ListSupportRoleRequest)(nil), "proto.ListSupportRoleRequest")
	proto.RegisterType((*GetSupportRoleRequest)(nil), "proto.GetSupportRoleRequest")
	proto.RegisterType((*Orgs)(nil), "proto.Orgs")
	proto.RegisterType((*ListOrgRequest)(nil), "proto.ListOrgRequest")
	proto.RegisterType((*GetOrgRequest)(nil), "proto.GetOrgRequest")
	proto.RegisterType((*NewAnswerRequest)(nil), "proto.NewAnswerRequest")
	proto.RegisterType((*Answer)(nil), "proto.Answer")
	proto.RegisterType((*Answers)(nil), "proto.Answers")
	proto.RegisterType((*SupportRole)(nil), "proto.SupportRole")
	proto.RegisterType((*Org)(nil), "proto.Org")
	proto.RegisterType((*NewAnswerResponse)(nil), "proto.NewAnswerResponse")
	proto.RegisterType((*DeleteAnswerResponse)(nil), "proto.DeleteAnswerResponse")
	proto.RegisterType((*AnswerIdRequest)(nil), "proto.AnswerIdRequest")
	proto.RegisterType((*SupportRoles)(nil), "proto.SupportRoles")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 929 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x96, 0xe3, 0xc4, 0xb1, 0x8f, 0x7f, 0x33, 0x4d, 0xd2, 0xc5, 0x45, 0xc4, 0x5d, 0x44, 0x13,
	0x90, 0x70, 0x90, 0xb9, 0x40, 0x08, 0x81, 0x54, 0x15, 0x11, 0x22, 0xb5, 0x4d, 0xea, 0x16, 0x71,
	0xb9, 0x9a, 0xec, 0x9e, 0x4e, 0x46, 0xec, 0xce, 0x6c, 0x67, 0xc6, 0x8d, 0xcc, 0xdb, 0x70, 0xc1,
	0x93, 0xf0, 0x0e, 0x3c, 0x09, 0x0f, 0x80, 0xe6, 0x67, 0xb7, 0x1b, 0xd2, 0x48, 0xe1, 0xae, 0x57,
	0x9e, 0xf9, 0xe6, 0x1b, 0xcf, 0xf9, 0xbe, 0xf3, 0xb3, 0x30, 0xd4, 0xa8, 0xde, 0xf2, 0x14, 0xe7,
	0xa5, 0x92, 0x46, 0x92, 0x2d, 0xf7, 0x33, 0x3d, 0x60, 0x52, 0xb2, 0x1c, 0x8f, 0xdd, 0xee, 0x62,
	0xf5, 0xfa, 0xd8, 0xf0, 0x02, 0xb5, 0xa1, 0x45, 0xe9, 0x79, 0xf1, 0x31, 0xec, 0x3f, 0xe5, 0xda,
	0xbc, 0x5c, 0x95, 0xa5, 0x54, 0x66, 0x29, 0x73, 0x5c, 0xe2, 0x9b, 0x15, 0x6a, 0x43, 0xf6, 0xa0,
	0x23, 0x15, 0x4b, 0x78, 0x16, 0xb5, 0x66, 0xad, 0xa3, 0xde, 0x72, 0x4b, 0x2a, 0x76, 0x9a, 0xc5,
	0x87, 0xb0, 0x77, 0x82, 0xef, 0xe3, 0x8f, 0x60, 0xa3, 0xe6, 0x6e, 0xf0, 0x2c, 0x7e, 0x04, 0x9b,
	0x67, 0x8a, 0x69, 0xf2, 0x09, 0x6c, 0x4a, 0xc5, 0x74, 0xd4, 0x9a, 0xb5, 0x8f, 0xfa, 0x0b, 0xf0,
	0xef, 0xce, 0xcf, 0x14, 0x5b, 0x3a, 0x3c, 0x9e, 0xc0, 0xc8, 0x46, 0x60, 0x01, 0xff, 0x4f, 0xf1,
	0x01, 0x0c, 0x4f, 0xb0, 0x01, 0xdc, 0xf8, 0xeb, 0x3f, 0x5b, 0x30, 0x79, 0x8e, 0x57, 0x8f, 0x85,
	0xbe, 0x42, 0x75, 0x0b, 0x89, 0x7c, 0x09, 0xf7, 0x34, 0xe6, 0x89, 0xf6, 0x91, 0x26, 0x4a, 0xe6,
	0x68, 0xc5, 0x6c, 0x38, 0xc2, 0x44, 0x63, 0xde, 0xd0, 0x70, 0x9a, 0x91, 0x47, 0x30, 0xb6, 0xf4,
	0x94, 0x16, 0x25, 0xe5, 0x4c, 0x58, 0x6a, 0xdb, 0x51, 0x87, 0x1a, 0xf3, 0x27, 0x01, 0x3d, 0xcd,
	0xc8, 0x17, 0xb0, 0x53, 0x70, 0x91, 0x5c, 0xca, 0x95, 0xd2, 0x49, 0x99, 0x63, 0xc6, 0x30, 0x8b,
	0x36, 0x1d, 0x73, 0x5c, 0x70, 0xf1, 0xb3, 0xc5, 0xcf, 0x3d, 0x1c, 0xff, 0xdd, 0x82, 0x8e, 0x0f,
	0xf2, 0x03, 0x8c, 0x8e, 0x7c, 0x0b, 0x90, 0x2a, 0xa4, 0x06, 0xb3, 0x84, 0x9a, 0x68, 0x6b, 0xd6,
	0x3a, 0xea, 0x2f, 0xa6, 0x73, 0x5f, 0x30, 0xf3, 0xaa, 0x60, 0xe6, 0xaf, 0xaa, 0x82, 0x59, 0xf6,
	0x02, 0xfb, 0xb1, 0x89, 0x17, 0xb0, 0xed, 0x75, 0x69, 0x72, 0x08, 0xdb, 0xd4, 0x2f, 0x43, 0x86,
	0x87, 0x21, 0xc3, 0x21, 0x3b, 0xd5, 0x69, 0xfc, 0x4f, 0x0b, 0xfa, 0x0d, 0x51, 0x37, 0x1c, 0x21,
	0xb0, 0x29, 0x68, 0x81, 0xc1, 0x02, 0xb7, 0x26, 0x11, 0x6c, 0xa7, 0xb2, 0x28, 0x50, 0x98, 0x20,
	0xb7, 0xda, 0x92, 0x8f, 0xa1, 0x57, 0x50, 0x91, 0x51, 0x23, 0xd5, 0xda, 0x09, 0xec, 0x2e, 0xdf,
	0x01, 0x64, 0x02, 0xed, 0x95, 0x2c, 0x9c, 0xa6, 0xde, 0xd2, 0x2e, 0xc9, 0x03, 0xe8, 0xd5, 0xc6,
	0x44, 0x1d, 0x87, 0x77, 0x2b, 0x43, 0xc8, 0x01, 0xf4, 0x9b, 0xce, 0x6e, 0xbb, 0x63, 0x48, 0xdf,
	0xd9, 0x7a, 0xdd, 0xaa, 0xee, 0xff, 0xb1, 0xea, 0x8f, 0x0e, 0xb4, 0xcf, 0x14, 0xbb, 0x21, 0xf7,
	0x53, 0x18, 0xd6, 0x6f, 0x36, 0x74, 0x0f, 0x2a, 0xf0, 0xb9, 0xd5, 0xff, 0x11, 0x74, 0x73, 0xc9,
	0x64, 0xb2, 0x52, 0x79, 0x65, 0x80, 0xdd, 0xff, 0xa2, 0x72, 0x6b, 0x17, 0x93, 0x34, 0x0f, 0xc9,
	0x75, 0x6b, 0x9b, 0xfd, 0x54, 0xb1, 0xe4, 0xcd, 0x8a, 0x0a, 0xc3, 0xcd, 0x3a, 0x29, 0xa8, 0x58,
	0x47, 0x5b, 0xb3, 0xb6, 0xcd, 0x7e, 0xaa, 0xd8, 0x8b, 0x80, 0x3f, 0xa3, 0x62, 0x4d, 0x66, 0x30,
	0x48, 0x5d, 0x7b, 0x6b, 0x4f, 0xeb, 0x38, 0x1a, 0xa4, 0xb6, 0xc9, 0xb5, 0x63, 0x1c, 0xc2, 0x98,
	0xe6, 0x0a, 0x69, 0xb6, 0xae, 0x2b, 0xc9, 0x3b, 0x33, 0x0a, 0x70, 0x55, 0x48, 0xdf, 0x41, 0x9f,
	0xa6, 0x86, 0x4b, 0x91, 0xd8, 0xe9, 0x72, 0x07, 0x7b, 0xc0, 0xd3, 0x2d, 0xe0, 0x5e, 0xf1, 0x97,
	0x73, 0x99, 0x52, 0xbb, 0x88, 0x7a, 0xe1, 0x15, 0x07, 0x3f, 0x0d, 0x28, 0xf9, 0x0c, 0x46, 0xb5,
	0x61, 0xda, 0xf0, 0x3c, 0x8f, 0xc0, 0x77, 0x40, 0x85, 0xbe, 0xb4, 0x20, 0x79, 0x08, 0x03, 0x9b,
	0xe8, 0x92, 0x4b, 0x81, 0xb6, 0x28, 0xfb, 0x8e, 0xd4, 0x2f, 0xb8, 0x38, 0x0f, 0x10, 0x39, 0x86,
	0x5d, 0x4b, 0x51, 0x78, 0x81, 0xb9, 0x4e, 0x5e, 0x4b, 0x95, 0x14, 0x98, 0x71, 0x1a, 0x0d, 0x1c,
	0xd5, 0x36, 0xd0, 0xd2, 0x1d, 0xfd, 0x24, 0xd5, 0x33, 0x7b, 0x40, 0x3e, 0xf7, 0x5d, 0x15, 0x2e,
	0x18, 0x99, 0x5c, 0x71, 0x11, 0x0d, 0x7d, 0x94, 0x35, 0xfb, 0x95, 0xfc, 0x95, 0x0b, 0x9b, 0xd6,
	0x4a, 0x0e, 0x0a, 0x66, 0x2e, 0xa3, 0x91, 0x4f, 0x6b, 0x10, 0xe3, 0x30, 0x5b, 0x6f, 0x95, 0x61,
	0xeb, 0x12, 0xa3, 0xb1, 0xaf, 0xb7, 0x60, 0xca, 0xba, 0x44, 0x4b, 0xb8, 0xa0, 0xe9, 0x6f, 0x5c,
	0xb0, 0x44, 0x2a, 0x16, 0x4d, 0x7c, 0x6e, 0x02, 0x64, 0xab, 0x69, 0x0a, 0xdd, 0x94, 0x1a, 0x64,
	0xb6, 0xfa, 0x77, 0x7c, 0x35, 0x57, 0x7b, 0xdf, 0x34, 0xc2, 0xd0, 0xd4, 0x44, 0xa4, 0x6a, 0x1a,
	0xb7, 0xb5, 0x5e, 0x5f, 0x72, 0x6d, 0x92, 0x52, 0x61, 0x8a, 0x19, 0x0a, 0xa3, 0xa3, 0x7b, 0x5e,
	0x85, 0x85, 0xcf, 0x6b, 0x94, 0xc4, 0x30, 0x90, 0x8a, 0x51, 0xc1, 0x7f, 0xf7, 0x19, 0xd9, 0xf5,
	0x22, 0x9a, 0x98, 0x0d, 0x41, 0x1b, 0x65, 0x1f, 0x5d, 0x47, 0x7b, 0x3e, 0x84, 0x6a, 0x6f, 0xbb,
	0xed, 0x2d, 0xcf, 0xd0, 0x17, 0xee, 0xbe, 0x8b, 0xbe, 0xeb, 0x00, 0x5b, 0xb9, 0xa1, 0x39, 0xef,
	0xd7, 0xcd, 0x19, 0x7f, 0x0f, 0x3b, 0x8d, 0x71, 0xae, 0x4b, 0x29, 0xb4, 0xeb, 0x7d, 0xbd, 0x4a,
	0x53, 0xd4, 0xda, 0x75, 0x4d, 0x77, 0x59, 0x6d, 0x43, 0x2b, 0x6d, 0xd4, 0x9f, 0x83, 0xaf, 0x60,
	0xf7, 0x47, 0xcc, 0xd1, 0xe0, 0x5d, 0xff, 0x21, 0x7e, 0x08, 0x63, 0xcf, 0x3d, 0xcd, 0x6e, 0xfb,
	0xc6, 0x9c, 0xc0, 0xa0, 0x31, 0xad, 0x34, 0xf9, 0x06, 0x86, 0xcd, 0x61, 0x5d, 0x4d, 0x3b, 0x12,
	0xa6, 0x5d, 0xf3, 0x83, 0x38, 0xd0, 0x8d, 0x8b, 0x8b, 0xbf, 0x5a, 0xd0, 0x7d, 0x61, 0x9f, 0xb0,
	0xa6, 0xfd, 0x00, 0xbd, 0x5a, 0x29, 0xb9, 0x1f, 0xee, 0xfe, 0xf7, 0x53, 0x36, 0x8d, 0x6e, 0x1e,
	0x04, 0x49, 0x0b, 0xe8, 0x9d, 0xa0, 0x09, 0xf7, 0xf7, 0xaf, 0x4d, 0xda, 0x5a, 0xca, 0xf4, 0xfa,
	0x04, 0x26, 0x4f, 0x60, 0xd0, 0xb4, 0xe7, 0xd6, 0x6b, 0x0f, 0x02, 0xfe, 0x3e, 0x2f, 0x2f, 0x3a,
	0xee, 0xec, 0xeb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x87, 0x31, 0x80, 0xfb, 0x67, 0x08, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QuestionClient is the client API for Question service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QuestionClient interface {
	//    rpc GetOrg(GetOrgRequest) returns (Org);
	//    rpc ListOrg(ListOrgRequest) returns (Orgs);
	//    rpc GetSupportRole(GetSupportRoleRequest) returns (SupportRoles);
	//    rpc ListSupportRole(ListSupportRoleRequest) returns (SupportRoles);
	NewAnswer(ctx context.Context, in *NewAnswerRequest, opts ...grpc.CallOption) (*NewAnswerResponse, error)
	GetAnswer(ctx context.Context, in *AnswerIdRequest, opts ...grpc.CallOption) (*Answer, error)
	DeleteAnswer(ctx context.Context, in *AnswerIdRequest, opts ...grpc.CallOption) (*DeleteAnswerResponse, error)
}

type questionClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestionClient(cc grpc.ClientConnInterface) QuestionClient {
	return &questionClient{cc}
}

func (c *questionClient) NewAnswer(ctx context.Context, in *NewAnswerRequest, opts ...grpc.CallOption) (*NewAnswerResponse, error) {
	out := new(NewAnswerResponse)
	err := c.cc.Invoke(ctx, "/proto.Question/NewAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetAnswer(ctx context.Context, in *AnswerIdRequest, opts ...grpc.CallOption) (*Answer, error) {
	out := new(Answer)
	err := c.cc.Invoke(ctx, "/proto.Question/GetAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) DeleteAnswer(ctx context.Context, in *AnswerIdRequest, opts ...grpc.CallOption) (*DeleteAnswerResponse, error) {
	out := new(DeleteAnswerResponse)
	err := c.cc.Invoke(ctx, "/proto.Question/DeleteAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionServer is the server API for Question service.
type QuestionServer interface {
	//    rpc GetOrg(GetOrgRequest) returns (Org);
	//    rpc ListOrg(ListOrgRequest) returns (Orgs);
	//    rpc GetSupportRole(GetSupportRoleRequest) returns (SupportRoles);
	//    rpc ListSupportRole(ListSupportRoleRequest) returns (SupportRoles);
	NewAnswer(context.Context, *NewAnswerRequest) (*NewAnswerResponse, error)
	GetAnswer(context.Context, *AnswerIdRequest) (*Answer, error)
	DeleteAnswer(context.Context, *AnswerIdRequest) (*DeleteAnswerResponse, error)
}

// UnimplementedQuestionServer can be embedded to have forward compatible implementations.
type UnimplementedQuestionServer struct {
}

func (*UnimplementedQuestionServer) NewAnswer(ctx context.Context, req *NewAnswerRequest) (*NewAnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewAnswer not implemented")
}
func (*UnimplementedQuestionServer) GetAnswer(ctx context.Context, req *AnswerIdRequest) (*Answer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnswer not implemented")
}
func (*UnimplementedQuestionServer) DeleteAnswer(ctx context.Context, req *AnswerIdRequest) (*DeleteAnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAnswer not implemented")
}

func RegisterQuestionServer(s *grpc.Server, srv QuestionServer) {
	s.RegisterService(&_Question_serviceDesc, srv)
}

func _Question_NewAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).NewAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/NewAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).NewAnswer(ctx, req.(*NewAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/GetAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetAnswer(ctx, req.(*AnswerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_DeleteAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).DeleteAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/DeleteAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).DeleteAnswer(ctx, req.(*AnswerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Question_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Question",
	HandlerType: (*QuestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewAnswer",
			Handler:    _Question_NewAnswer_Handler,
		},
		{
			MethodName: "GetAnswer",
			Handler:    _Question_GetAnswer_Handler,
		},
		{
			MethodName: "DeleteAnswer",
			Handler:    _Question_DeleteAnswer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
