// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListSupportRoleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSupportRoleRequest) Reset()         { *m = ListSupportRoleRequest{} }
func (m *ListSupportRoleRequest) String() string { return proto.CompactTextString(m) }
func (*ListSupportRoleRequest) ProtoMessage()    {}
func (*ListSupportRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ListSupportRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSupportRoleRequest.Unmarshal(m, b)
}
func (m *ListSupportRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSupportRoleRequest.Marshal(b, m, deterministic)
}
func (m *ListSupportRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSupportRoleRequest.Merge(m, src)
}
func (m *ListSupportRoleRequest) XXX_Size() int {
	return xxx_messageInfo_ListSupportRoleRequest.Size(m)
}
func (m *ListSupportRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSupportRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSupportRoleRequest proto.InternalMessageInfo

type GetSupportRoleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSupportRoleRequest) Reset()         { *m = GetSupportRoleRequest{} }
func (m *GetSupportRoleRequest) String() string { return proto.CompactTextString(m) }
func (*GetSupportRoleRequest) ProtoMessage()    {}
func (*GetSupportRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetSupportRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSupportRoleRequest.Unmarshal(m, b)
}
func (m *GetSupportRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSupportRoleRequest.Marshal(b, m, deterministic)
}
func (m *GetSupportRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSupportRoleRequest.Merge(m, src)
}
func (m *GetSupportRoleRequest) XXX_Size() int {
	return xxx_messageInfo_GetSupportRoleRequest.Size(m)
}
func (m *GetSupportRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSupportRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSupportRoleRequest proto.InternalMessageInfo

func (m *GetSupportRoleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Campaigns struct {
	Campaigns            []*Campaign `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Campaigns) Reset()         { *m = Campaigns{} }
func (m *Campaigns) String() string { return proto.CompactTextString(m) }
func (*Campaigns) ProtoMessage()    {}
func (*Campaigns) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Campaigns) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Campaigns.Unmarshal(m, b)
}
func (m *Campaigns) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Campaigns.Marshal(b, m, deterministic)
}
func (m *Campaigns) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaigns.Merge(m, src)
}
func (m *Campaigns) XXX_Size() int {
	return xxx_messageInfo_Campaigns.Size(m)
}
func (m *Campaigns) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaigns.DiscardUnknown(m)
}

var xxx_messageInfo_Campaigns proto.InternalMessageInfo

func (m *Campaigns) GetCampaigns() []*Campaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

type ListCampaignRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCampaignRequest) Reset()         { *m = ListCampaignRequest{} }
func (m *ListCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*ListCampaignRequest) ProtoMessage()    {}
func (*ListCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ListCampaignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCampaignRequest.Unmarshal(m, b)
}
func (m *ListCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCampaignRequest.Marshal(b, m, deterministic)
}
func (m *ListCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCampaignRequest.Merge(m, src)
}
func (m *ListCampaignRequest) XXX_Size() int {
	return xxx_messageInfo_ListCampaignRequest.Size(m)
}
func (m *ListCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCampaignRequest proto.InternalMessageInfo

type GetCampaignRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCampaignRequest) Reset()         { *m = GetCampaignRequest{} }
func (m *GetCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*GetCampaignRequest) ProtoMessage()    {}
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *GetCampaignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCampaignRequest.Unmarshal(m, b)
}
func (m *GetCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCampaignRequest.Marshal(b, m, deterministic)
}
func (m *GetCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCampaignRequest.Merge(m, src)
}
func (m *GetCampaignRequest) XXX_Size() int {
	return xxx_messageInfo_GetCampaignRequest.Size(m)
}
func (m *GetCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCampaignRequest proto.InternalMessageInfo

func (m *GetCampaignRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NewAnswerRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SelSupportRoleId     string   `protobuf:"bytes,2,opt,name=sel_support_role_id,json=selSupportRoleId,proto3" json:"sel_support_role_id,omitempty"`
	SelCampaignId        string   `protobuf:"bytes,3,opt,name=sel_campaign_id,json=selCampaignId,proto3" json:"sel_campaign_id,omitempty"`
	MinHoursPledged      string   `protobuf:"bytes,4,opt,name=min_hours_pledged,json=minHoursPledged,proto3" json:"min_hours_pledged,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAnswerRequest) Reset()         { *m = NewAnswerRequest{} }
func (m *NewAnswerRequest) String() string { return proto.CompactTextString(m) }
func (*NewAnswerRequest) ProtoMessage()    {}
func (*NewAnswerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *NewAnswerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAnswerRequest.Unmarshal(m, b)
}
func (m *NewAnswerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAnswerRequest.Marshal(b, m, deterministic)
}
func (m *NewAnswerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAnswerRequest.Merge(m, src)
}
func (m *NewAnswerRequest) XXX_Size() int {
	return xxx_messageInfo_NewAnswerRequest.Size(m)
}
func (m *NewAnswerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAnswerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewAnswerRequest proto.InternalMessageInfo

func (m *NewAnswerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewAnswerRequest) GetSelSupportRoleId() string {
	if m != nil {
		return m.SelSupportRoleId
	}
	return ""
}

func (m *NewAnswerRequest) GetSelCampaignId() string {
	if m != nil {
		return m.SelCampaignId
	}
	return ""
}

func (m *NewAnswerRequest) GetMinHoursPledged() string {
	if m != nil {
		return m.MinHoursPledged
	}
	return ""
}

type Answer struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// selected support role
	SelSupportRoleId string `protobuf:"bytes,2,opt,name=sel_support_role_id,json=selSupportRoleId,proto3" json:"sel_support_role_id,omitempty"`
	// selected campaign id
	SelCampaignId        string               `protobuf:"bytes,3,opt,name=sel_campaign_id,json=selCampaignId,proto3" json:"sel_campaign_id,omitempty"`
	MinHoursPledged      string               `protobuf:"bytes,4,opt,name=min_hours_pledged,json=minHoursPledged,proto3" json:"min_hours_pledged,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Answer) Reset()         { *m = Answer{} }
func (m *Answer) String() string { return proto.CompactTextString(m) }
func (*Answer) ProtoMessage()    {}
func (*Answer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *Answer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Answer.Unmarshal(m, b)
}
func (m *Answer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Answer.Marshal(b, m, deterministic)
}
func (m *Answer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Answer.Merge(m, src)
}
func (m *Answer) XXX_Size() int {
	return xxx_messageInfo_Answer.Size(m)
}
func (m *Answer) XXX_DiscardUnknown() {
	xxx_messageInfo_Answer.DiscardUnknown(m)
}

var xxx_messageInfo_Answer proto.InternalMessageInfo

func (m *Answer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Answer) GetSelSupportRoleId() string {
	if m != nil {
		return m.SelSupportRoleId
	}
	return ""
}

func (m *Answer) GetSelCampaignId() string {
	if m != nil {
		return m.SelCampaignId
	}
	return ""
}

func (m *Answer) GetMinHoursPledged() string {
	if m != nil {
		return m.MinHoursPledged
	}
	return ""
}

func (m *Answer) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Answers struct {
	Answers              []*Answer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Answers) Reset()         { *m = Answers{} }
func (m *Answers) String() string { return proto.CompactTextString(m) }
func (*Answers) ProtoMessage()    {}
func (*Answers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *Answers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Answers.Unmarshal(m, b)
}
func (m *Answers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Answers.Marshal(b, m, deterministic)
}
func (m *Answers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Answers.Merge(m, src)
}
func (m *Answers) XXX_Size() int {
	return xxx_messageInfo_Answers.Size(m)
}
func (m *Answers) XXX_DiscardUnknown() {
	xxx_messageInfo_Answers.DiscardUnknown(m)
}

var xxx_messageInfo_Answers proto.InternalMessageInfo

func (m *Answers) GetAnswers() []*Answer {
	if m != nil {
		return m.Answers
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName          string   `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Url                  string   `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	ChatgroupIds         string   `protobuf:"bytes,8,opt,name=chatgroup_ids,json=chatgroupIds,proto3" json:"chatgroup_ids,omitempty"`
	Campaign             string   `protobuf:"bytes,9,opt,name=campaign,proto3" json:"campaign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *User) GetChatgroupIds() string {
	if m != nil {
		return m.ChatgroupIds
	}
	return ""
}

func (m *User) GetCampaign() string {
	if m != nil {
		return m.Campaign
	}
	return ""
}

type SupportRole struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Mandatory            bool     `protobuf:"varint,4,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	Uom                  string   `protobuf:"bytes,5,opt,name=uom,proto3" json:"uom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupportRole) Reset()         { *m = SupportRole{} }
func (m *SupportRole) String() string { return proto.CompactTextString(m) }
func (*SupportRole) ProtoMessage()    {}
func (*SupportRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *SupportRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportRole.Unmarshal(m, b)
}
func (m *SupportRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportRole.Marshal(b, m, deterministic)
}
func (m *SupportRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportRole.Merge(m, src)
}
func (m *SupportRole) XXX_Size() int {
	return xxx_messageInfo_SupportRole.Size(m)
}
func (m *SupportRole) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportRole.DiscardUnknown(m)
}

var xxx_messageInfo_SupportRole proto.InternalMessageInfo

func (m *SupportRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SupportRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SupportRole) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *SupportRole) GetMandatory() bool {
	if m != nil {
		return m.Mandatory
	}
	return false
}

func (m *SupportRole) GetUom() string {
	if m != nil {
		return m.Uom
	}
	return ""
}

type Campaign struct {
	CampaignId        string               `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	CampaignName      string               `protobuf:"bytes,2,opt,name=campaign_name,json=campaignName,proto3" json:"campaign_name,omitempty"`
	LogoUrl           string               `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Goal              string               `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	CrgQuantityMany   []string             `protobuf:"bytes,5,rep,name=crg_quantity_many,json=crgQuantityMany,proto3" json:"crg_quantity_many,omitempty"`
	CrgIdsMany        []string             `protobuf:"bytes,6,rep,name=crg_ids_many,json=crgIdsMany,proto3" json:"crg_ids_many,omitempty"`
	AlreadyPledged    string               `protobuf:"bytes,7,opt,name=already_pledged,json=alreadyPledged,proto3" json:"already_pledged,omitempty"`
	ActionTime        *timestamp.Timestamp `protobuf:"bytes,8,opt,name=action_time,json=actionTime,proto3" json:"action_time,omitempty"`
	ActionLocation    string               `protobuf:"bytes,9,opt,name=action_location,json=actionLocation,proto3" json:"action_location,omitempty"`
	CampaignStill     string               `protobuf:"bytes,10,opt,name=campaign_still,json=campaignStill,proto3" json:"campaign_still,omitempty"`
	MinPioneers       string               `protobuf:"bytes,11,opt,name=min_pioneers,json=minPioneers,proto3" json:"min_pioneers,omitempty"`
	MinRebelsForMedia string               `protobuf:"bytes,12,opt,name=min_rebels_for_media,json=minRebelsForMedia,proto3" json:"min_rebels_for_media,omitempty"`
	MinRebelsToWin    string               `protobuf:"bytes,13,opt,name=min_rebels_to_win,json=minRebelsToWin,proto3" json:"min_rebels_to_win,omitempty"`
	ActionType        string               `protobuf:"bytes,15,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	BackingOrg        []string             `protobuf:"bytes,16,rep,name=backing_org,json=backingOrg,proto3" json:"backing_org,omitempty"`
	Category          string               `protobuf:"bytes,17,opt,name=category,proto3" json:"category,omitempty"`
	Contact           string               `protobuf:"bytes,18,opt,name=contact,proto3" json:"contact,omitempty"`
	HistPrecedents    string               `protobuf:"bytes,19,opt,name=hist_precedents,json=histPrecedents,proto3" json:"hist_precedents,omitempty"`
	Organization      string               `protobuf:"bytes,20,opt,name=organization,proto3" json:"organization,omitempty"`
	Strategy          string               `protobuf:"bytes,21,opt,name=strategy,proto3" json:"strategy,omitempty"`
	VideoUrl          []string             `protobuf:"bytes,22,rep,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Uom               string               `protobuf:"bytes,23,opt,name=uom,proto3" json:"uom,omitempty"`
	// Types that are valid to be assigned to ActionLength:
	//	*Campaign_ActionLengthString
	//	*Campaign_ActionLengthInt
	ActionLength         isCampaign_ActionLength `protobuf_oneof:"action_length"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Campaign) Reset()         { *m = Campaign{} }
func (m *Campaign) String() string { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()    {}
func (*Campaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *Campaign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Campaign.Unmarshal(m, b)
}
func (m *Campaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Campaign.Marshal(b, m, deterministic)
}
func (m *Campaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaign.Merge(m, src)
}
func (m *Campaign) XXX_Size() int {
	return xxx_messageInfo_Campaign.Size(m)
}
func (m *Campaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaign.DiscardUnknown(m)
}

var xxx_messageInfo_Campaign proto.InternalMessageInfo

func (m *Campaign) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *Campaign) GetCampaignName() string {
	if m != nil {
		return m.CampaignName
	}
	return ""
}

func (m *Campaign) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *Campaign) GetGoal() string {
	if m != nil {
		return m.Goal
	}
	return ""
}

func (m *Campaign) GetCrgQuantityMany() []string {
	if m != nil {
		return m.CrgQuantityMany
	}
	return nil
}

func (m *Campaign) GetCrgIdsMany() []string {
	if m != nil {
		return m.CrgIdsMany
	}
	return nil
}

func (m *Campaign) GetAlreadyPledged() string {
	if m != nil {
		return m.AlreadyPledged
	}
	return ""
}

func (m *Campaign) GetActionTime() *timestamp.Timestamp {
	if m != nil {
		return m.ActionTime
	}
	return nil
}

func (m *Campaign) GetActionLocation() string {
	if m != nil {
		return m.ActionLocation
	}
	return ""
}

func (m *Campaign) GetCampaignStill() string {
	if m != nil {
		return m.CampaignStill
	}
	return ""
}

func (m *Campaign) GetMinPioneers() string {
	if m != nil {
		return m.MinPioneers
	}
	return ""
}

func (m *Campaign) GetMinRebelsForMedia() string {
	if m != nil {
		return m.MinRebelsForMedia
	}
	return ""
}

func (m *Campaign) GetMinRebelsToWin() string {
	if m != nil {
		return m.MinRebelsToWin
	}
	return ""
}

func (m *Campaign) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

func (m *Campaign) GetBackingOrg() []string {
	if m != nil {
		return m.BackingOrg
	}
	return nil
}

func (m *Campaign) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Campaign) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *Campaign) GetHistPrecedents() string {
	if m != nil {
		return m.HistPrecedents
	}
	return ""
}

func (m *Campaign) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *Campaign) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *Campaign) GetVideoUrl() []string {
	if m != nil {
		return m.VideoUrl
	}
	return nil
}

func (m *Campaign) GetUom() string {
	if m != nil {
		return m.Uom
	}
	return ""
}

type isCampaign_ActionLength interface {
	isCampaign_ActionLength()
}

type Campaign_ActionLengthString struct {
	ActionLengthString string `protobuf:"bytes,24,opt,name=action_length_string,json=actionLengthString,proto3,oneof"`
}

type Campaign_ActionLengthInt struct {
	ActionLengthInt uint32 `protobuf:"varint,25,opt,name=action_length_int,json=actionLengthInt,proto3,oneof"`
}

func (*Campaign_ActionLengthString) isCampaign_ActionLength() {}

func (*Campaign_ActionLengthInt) isCampaign_ActionLength() {}

func (m *Campaign) GetActionLength() isCampaign_ActionLength {
	if m != nil {
		return m.ActionLength
	}
	return nil
}

func (m *Campaign) GetActionLengthString() string {
	if x, ok := m.GetActionLength().(*Campaign_ActionLengthString); ok {
		return x.ActionLengthString
	}
	return ""
}

func (m *Campaign) GetActionLengthInt() uint32 {
	if x, ok := m.GetActionLength().(*Campaign_ActionLengthInt); ok {
		return x.ActionLengthInt
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Campaign) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Campaign_ActionLengthString)(nil),
		(*Campaign_ActionLengthInt)(nil),
	}
}

type NewAnswerResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAnswerResponse) Reset()         { *m = NewAnswerResponse{} }
func (m *NewAnswerResponse) String() string { return proto.CompactTextString(m) }
func (*NewAnswerResponse) ProtoMessage()    {}
func (*NewAnswerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *NewAnswerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAnswerResponse.Unmarshal(m, b)
}
func (m *NewAnswerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAnswerResponse.Marshal(b, m, deterministic)
}
func (m *NewAnswerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAnswerResponse.Merge(m, src)
}
func (m *NewAnswerResponse) XXX_Size() int {
	return xxx_messageInfo_NewAnswerResponse.Size(m)
}
func (m *NewAnswerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAnswerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewAnswerResponse proto.InternalMessageInfo

func (m *NewAnswerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *NewAnswerResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAnswerResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAnswerResponse) Reset()         { *m = DeleteAnswerResponse{} }
func (m *DeleteAnswerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAnswerResponse) ProtoMessage()    {}
func (*DeleteAnswerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *DeleteAnswerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAnswerResponse.Unmarshal(m, b)
}
func (m *DeleteAnswerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAnswerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAnswerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAnswerResponse.Merge(m, src)
}
func (m *DeleteAnswerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAnswerResponse.Size(m)
}
func (m *DeleteAnswerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAnswerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAnswerResponse proto.InternalMessageInfo

func (m *DeleteAnswerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AnswerIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerIdRequest) Reset()         { *m = AnswerIdRequest{} }
func (m *AnswerIdRequest) String() string { return proto.CompactTextString(m) }
func (*AnswerIdRequest) ProtoMessage()    {}
func (*AnswerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *AnswerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerIdRequest.Unmarshal(m, b)
}
func (m *AnswerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerIdRequest.Marshal(b, m, deterministic)
}
func (m *AnswerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerIdRequest.Merge(m, src)
}
func (m *AnswerIdRequest) XXX_Size() int {
	return xxx_messageInfo_AnswerIdRequest.Size(m)
}
func (m *AnswerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerIdRequest proto.InternalMessageInfo

func (m *AnswerIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SupportRoles struct {
	SupportRoles         []*SupportRole `protobuf:"bytes,1,rep,name=support_roles,json=supportRoles,proto3" json:"support_roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SupportRoles) Reset()         { *m = SupportRoles{} }
func (m *SupportRoles) String() string { return proto.CompactTextString(m) }
func (*SupportRoles) ProtoMessage()    {}
func (*SupportRoles) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *SupportRoles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportRoles.Unmarshal(m, b)
}
func (m *SupportRoles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportRoles.Marshal(b, m, deterministic)
}
func (m *SupportRoles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportRoles.Merge(m, src)
}
func (m *SupportRoles) XXX_Size() int {
	return xxx_messageInfo_SupportRoles.Size(m)
}
func (m *SupportRoles) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportRoles.DiscardUnknown(m)
}

var xxx_messageInfo_SupportRoles proto.InternalMessageInfo

func (m *SupportRoles) GetSupportRoles() []*SupportRole {
	if m != nil {
		return m.SupportRoles
	}
	return nil
}

type ListAnswersRequest struct {
	SupportRoleId        string   `protobuf:"bytes,1,opt,name=support_role_id,json=supportRoleId,proto3" json:"support_role_id,omitempty"`
	CampaignId           string   `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAnswersRequest) Reset()         { *m = ListAnswersRequest{} }
func (m *ListAnswersRequest) String() string { return proto.CompactTextString(m) }
func (*ListAnswersRequest) ProtoMessage()    {}
func (*ListAnswersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{15}
}

func (m *ListAnswersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAnswersRequest.Unmarshal(m, b)
}
func (m *ListAnswersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAnswersRequest.Marshal(b, m, deterministic)
}
func (m *ListAnswersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAnswersRequest.Merge(m, src)
}
func (m *ListAnswersRequest) XXX_Size() int {
	return xxx_messageInfo_ListAnswersRequest.Size(m)
}
func (m *ListAnswersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAnswersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAnswersRequest proto.InternalMessageInfo

func (m *ListAnswersRequest) GetSupportRoleId() string {
	if m != nil {
		return m.SupportRoleId
	}
	return ""
}

func (m *ListAnswersRequest) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

type ListUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserRequest) Reset()         { *m = ListUserRequest{} }
func (m *ListUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserRequest) ProtoMessage()    {}
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{16}
}

func (m *ListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequest.Unmarshal(m, b)
}
func (m *ListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequest.Marshal(b, m, deterministic)
}
func (m *ListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequest.Merge(m, src)
}
func (m *ListUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserRequest.Size(m)
}
func (m *ListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequest proto.InternalMessageInfo

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{17}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{18}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type MigrateRequest struct {
	Datapath             string   `protobuf:"bytes,1,opt,name=datapath,proto3" json:"datapath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateRequest) Reset()         { *m = MigrateRequest{} }
func (m *MigrateRequest) String() string { return proto.CompactTextString(m) }
func (*MigrateRequest) ProtoMessage()    {}
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{19}
}

func (m *MigrateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateRequest.Unmarshal(m, b)
}
func (m *MigrateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateRequest.Marshal(b, m, deterministic)
}
func (m *MigrateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateRequest.Merge(m, src)
}
func (m *MigrateRequest) XXX_Size() int {
	return xxx_messageInfo_MigrateRequest.Size(m)
}
func (m *MigrateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateRequest proto.InternalMessageInfo

func (m *MigrateRequest) GetDatapath() string {
	if m != nil {
		return m.Datapath
	}
	return ""
}

func init() {
	proto.RegisterType((*ListSupportRoleRequest)(nil), "proto.ListSupportRoleRequest")
	proto.RegisterType((*GetSupportRoleRequest)(nil), "proto.GetSupportRoleRequest")
	proto.RegisterType((*Campaigns)(nil), "proto.Campaigns")
	proto.RegisterType((*ListCampaignRequest)(nil), "proto.ListCampaignRequest")
	proto.RegisterType((*GetCampaignRequest)(nil), "proto.GetCampaignRequest")
	proto.RegisterType((*NewAnswerRequest)(nil), "proto.NewAnswerRequest")
	proto.RegisterType((*Answer)(nil), "proto.Answer")
	proto.RegisterType((*Answers)(nil), "proto.Answers")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*SupportRole)(nil), "proto.SupportRole")
	proto.RegisterType((*Campaign)(nil), "proto.Campaign")
	proto.RegisterType((*NewAnswerResponse)(nil), "proto.NewAnswerResponse")
	proto.RegisterType((*DeleteAnswerResponse)(nil), "proto.DeleteAnswerResponse")
	proto.RegisterType((*AnswerIdRequest)(nil), "proto.AnswerIdRequest")
	proto.RegisterType((*SupportRoles)(nil), "proto.SupportRoles")
	proto.RegisterType((*ListAnswersRequest)(nil), "proto.ListAnswersRequest")
	proto.RegisterType((*ListUserRequest)(nil), "proto.ListUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "proto.GetUserRequest")
	proto.RegisterType((*Users)(nil), "proto.Users")
	proto.RegisterType((*MigrateRequest)(nil), "proto.MigrateRequest")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 1263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x73, 0xd4, 0x46,
	0x13, 0x66, 0x6d, 0xd6, 0xbb, 0xdb, 0xfb, 0x65, 0x8f, 0x3f, 0x18, 0x04, 0x14, 0x8b, 0xde, 0x37,
	0xc1, 0xa1, 0xc0, 0x24, 0xce, 0x21, 0x90, 0x14, 0xa9, 0x02, 0x12, 0x8c, 0xab, 0x80, 0xc0, 0x02,
	0x95, 0x53, 0x4a, 0x35, 0x96, 0x06, 0x79, 0x2a, 0x92, 0x46, 0xcc, 0xcc, 0x42, 0x6d, 0x72, 0xce,
	0xef, 0xc8, 0x29, 0x7f, 0x29, 0x3f, 0x25, 0xe7, 0xd4, 0x7c, 0x69, 0xb5, 0x5a, 0x3b, 0x95, 0x63,
	0x4e, 0x52, 0x77, 0x3f, 0x3d, 0xd3, 0x3d, 0xfd, 0xf4, 0xf4, 0xc0, 0x50, 0x52, 0xf1, 0x81, 0xc5,
	0xf4, 0xa0, 0x14, 0x5c, 0x71, 0xd4, 0x36, 0x9f, 0xe0, 0x7a, 0xca, 0x79, 0x9a, 0xd1, 0xbb, 0x46,
	0x3a, 0x99, 0xbd, 0xbb, 0xab, 0x58, 0x4e, 0xa5, 0x22, 0x79, 0x69, 0x71, 0xc1, 0x95, 0x26, 0x80,
	0xe6, 0xa5, 0x9a, 0x5b, 0x63, 0x88, 0x61, 0xef, 0x19, 0x93, 0xea, 0xf5, 0xac, 0x2c, 0xb9, 0x50,
	0x53, 0x9e, 0xd1, 0x29, 0x7d, 0x3f, 0xa3, 0x52, 0x85, 0x37, 0x61, 0xf7, 0x88, 0x9e, 0x61, 0x40,
	0x23, 0x58, 0x63, 0x09, 0x6e, 0x4d, 0x5a, 0xfb, 0xbd, 0xe9, 0x1a, 0x4b, 0xc2, 0xaf, 0xa1, 0xf7,
	0x98, 0xe4, 0x25, 0x61, 0x69, 0x21, 0xd1, 0x1d, 0xe8, 0xc5, 0x5e, 0xc0, 0xad, 0xc9, 0xfa, 0x7e,
	0xff, 0x70, 0x6c, 0xb7, 0x3a, 0xf0, 0xa0, 0xe9, 0x02, 0x11, 0xee, 0xc2, 0xb6, 0xde, 0xbe, 0x32,
	0xb9, 0xbd, 0xff, 0x0f, 0xe8, 0x88, 0x36, 0xb5, 0x2b, 0x1b, 0xff, 0xd1, 0x82, 0xcd, 0x17, 0xf4,
	0xe3, 0xc3, 0x42, 0x7e, 0xa4, 0xe2, 0x1c, 0x10, 0xba, 0x03, 0xdb, 0x92, 0x66, 0x91, 0xb4, 0x79,
	0x44, 0x82, 0x67, 0x34, 0x62, 0x09, 0x5e, 0x33, 0x80, 0x4d, 0x49, 0xb3, 0x5a, 0x86, 0xc7, 0x09,
	0xfa, 0x14, 0xc6, 0x1a, 0xee, 0x23, 0xd4, 0xd0, 0x75, 0x03, 0x1d, 0x4a, 0x9a, 0xf9, 0x80, 0x8e,
	0x13, 0x74, 0x0b, 0xb6, 0x72, 0x56, 0x44, 0xa7, 0x7c, 0x26, 0x64, 0x54, 0x66, 0x34, 0x49, 0x69,
	0x82, 0x2f, 0x1a, 0xe4, 0x38, 0x67, 0xc5, 0x53, 0xad, 0x7f, 0x69, 0xd5, 0xe1, 0x9f, 0x2d, 0xd8,
	0xb0, 0x41, 0xfe, 0x07, 0xa3, 0x43, 0xf7, 0x01, 0x62, 0x41, 0x89, 0xa2, 0x49, 0x44, 0x14, 0x6e,
	0x4f, 0x5a, 0xfb, 0xfd, 0xc3, 0xe0, 0xc0, 0x72, 0xe6, 0xc0, 0x73, 0xe6, 0xe0, 0x8d, 0x27, 0xd5,
	0xb4, 0xe7, 0xd0, 0x0f, 0x55, 0x78, 0x08, 0x1d, 0x9b, 0x97, 0x44, 0x37, 0xa1, 0x43, 0xec, 0xaf,
	0xab, 0xfa, 0xd0, 0x55, 0xdd, 0x55, 0xc7, 0x5b, 0xc3, 0xbf, 0x5a, 0x70, 0xf1, 0xad, 0x3c, 0xe3,
	0x28, 0xae, 0x01, 0xbc, 0x63, 0x42, 0xaa, 0xa8, 0x20, 0x39, 0x75, 0x27, 0xd0, 0x33, 0x9a, 0x17,
	0x24, 0xa7, 0xe8, 0x0a, 0xf4, 0x32, 0xe2, 0xad, 0x36, 0xe9, 0xae, 0x56, 0x18, 0xe3, 0x0e, 0xb4,
	0x69, 0x4e, 0x58, 0xe6, 0x72, 0xb4, 0x02, 0xba, 0x01, 0x83, 0x84, 0xc9, 0x32, 0x23, 0x73, 0xeb,
	0xd5, 0x36, 0xc6, 0xbe, 0xd3, 0x19, 0xc7, 0x3d, 0xd8, 0x20, 0x1f, 0x88, 0x22, 0x02, 0x6f, 0x18,
	0xa3, 0x93, 0xd0, 0x26, 0xac, 0xcf, 0x44, 0x86, 0x3b, 0x46, 0xa9, 0x7f, 0xd1, 0xff, 0x60, 0x18,
	0x9f, 0x12, 0x95, 0x0a, 0x3e, 0x2b, 0x23, 0x96, 0x48, 0xdc, 0x35, 0xb6, 0x41, 0xa5, 0x3c, 0x4e,
	0x24, 0x0a, 0xa0, 0xeb, 0x6b, 0x83, 0x7b, 0x36, 0x46, 0x2f, 0x87, 0xbf, 0x42, 0xbf, 0x56, 0xcc,
	0x95, 0xf4, 0x11, 0x5c, 0xac, 0x25, 0x6e, 0xfe, 0x11, 0x86, 0x4e, 0xcc, 0xf3, 0x9c, 0x16, 0xca,
	0x65, 0xec, 0x45, 0x74, 0x15, 0x7a, 0x39, 0x29, 0x12, 0xa2, 0xb8, 0x98, 0x9b, 0xa4, 0xbb, 0xd3,
	0x85, 0xc2, 0x44, 0xcf, 0x73, 0x97, 0xaf, 0xfe, 0x0d, 0x7f, 0xeb, 0x40, 0xd7, 0xf3, 0x03, 0x5d,
	0x87, 0x7e, 0x9d, 0x41, 0x36, 0x06, 0x88, 0x17, 0xf4, 0xd1, 0xb9, 0x7a, 0x40, 0x2d, 0xa8, 0x81,
	0x57, 0x9a, 0xa3, 0xbb, 0x0c, 0xdd, 0x8c, 0xa7, 0x3c, 0xd2, 0xe7, 0xe4, 0xa2, 0xd3, 0xf2, 0x5b,
	0x91, 0xe9, 0x5c, 0x52, 0x4e, 0x7c, 0x35, 0xcc, 0xbf, 0xa6, 0x64, 0x2c, 0xd2, 0xe8, 0xfd, 0x8c,
	0x14, 0x8a, 0xa9, 0x79, 0x94, 0x93, 0x62, 0x8e, 0xdb, 0x93, 0x75, 0x4d, 0xc9, 0x58, 0xa4, 0xaf,
	0x9c, 0xfe, 0x39, 0x29, 0xe6, 0x68, 0x02, 0x03, 0x8d, 0x65, 0x89, 0xb4, 0xb0, 0x0d, 0x03, 0x83,
	0x58, 0xa4, 0xc7, 0x89, 0x34, 0x88, 0x9b, 0x30, 0x26, 0x99, 0xa0, 0x24, 0x99, 0x57, 0xf4, 0xb6,
	0xb5, 0x1a, 0x39, 0xb5, 0x67, 0xf7, 0x37, 0xd0, 0x27, 0xb1, 0x62, 0xbc, 0x88, 0xf4, 0xb5, 0x68,
	0x8a, 0xf6, 0xcf, 0xf4, 0x06, 0x0b, 0xd7, 0x0a, 0xb3, 0x8b, 0x75, 0xce, 0x78, 0x4c, 0xf4, 0x8f,
	0xab, 0xea, 0xc8, 0xaa, 0x9f, 0x39, 0x2d, 0xfa, 0x04, 0x46, 0xd5, 0x81, 0x49, 0xc5, 0xb2, 0x0c,
	0x83, 0x6d, 0x4b, 0xaf, 0x7d, 0xad, 0x95, 0x9a, 0x90, 0xba, 0x2d, 0x4b, 0xc6, 0x0b, 0xaa, 0x3b,
	0xa5, 0x6f, 0x09, 0x99, 0xb3, 0xe2, 0xa5, 0x53, 0xa1, 0xbb, 0xb0, 0xa3, 0x21, 0x82, 0x9e, 0xd0,
	0x4c, 0x46, 0xef, 0xb8, 0x88, 0x72, 0x9a, 0x30, 0x82, 0x07, 0x06, 0xaa, 0xbb, 0x7a, 0x6a, 0x4c,
	0x4f, 0xb8, 0x78, 0xae, 0x0d, 0xe8, 0x33, 0xdb, 0xea, 0xce, 0x41, 0xf1, 0xe8, 0x23, 0x2b, 0xf0,
	0xd0, 0x46, 0x59, 0xa1, 0xdf, 0xf0, 0x1f, 0x99, 0xa9, 0xbb, 0x3f, 0x8b, 0x79, 0x49, 0xf1, 0xd8,
	0xd6, 0xdd, 0xe5, 0x3b, 0x2f, 0xa9, 0x06, 0x9c, 0x90, 0xf8, 0x67, 0x56, 0xa4, 0x11, 0x17, 0x29,
	0xde, 0xb4, 0xc7, 0xee, 0x54, 0x3f, 0x88, 0xd4, 0xf2, 0x5b, 0xd1, 0x54, 0xb3, 0x6e, 0xcb, 0xf3,
	0xdb, 0xca, 0x96, 0xac, 0x85, 0x22, 0xb1, 0xc2, 0xc8, 0x93, 0xd5, 0x88, 0xfa, 0x18, 0x4f, 0x99,
	0x54, 0x51, 0x29, 0x68, 0x4c, 0x13, 0x5a, 0x28, 0x89, 0xb7, 0x6d, 0x80, 0x5a, 0xfd, 0xb2, 0xd2,
	0xa2, 0x10, 0x06, 0x5c, 0xa4, 0xa4, 0x60, 0xbf, 0xd8, 0xc3, 0xde, 0xb1, 0xb4, 0xab, 0xeb, 0x74,
	0x08, 0x52, 0x09, 0xbd, 0xe9, 0x1c, 0xef, 0xda, 0x10, 0xbc, 0xac, 0xef, 0x88, 0x0f, 0x2c, 0xa1,
	0x96, 0x93, 0x7b, 0x26, 0xfa, 0xae, 0x51, 0x68, 0x52, 0xba, 0xa6, 0xb8, 0x54, 0x35, 0x05, 0x3a,
	0x84, 0x1d, 0x5f, 0x5e, 0x5a, 0xa4, 0xea, 0x34, 0x92, 0x4a, 0xb0, 0x22, 0xc5, 0x58, 0x43, 0x9e,
	0x5e, 0x98, 0x22, 0x57, 0x65, 0x63, 0x7c, 0x6d, 0x6c, 0xe8, 0x36, 0x6c, 0x2d, 0xfb, 0xb0, 0x42,
	0xe1, 0xcb, 0x93, 0xd6, 0xfe, 0xf0, 0xe9, 0x85, 0xe9, 0xb8, 0xee, 0x70, 0x5c, 0xa8, 0x47, 0x63,
	0x18, 0x2e, 0xa1, 0xc3, 0x07, 0xb0, 0x55, 0x9b, 0x58, 0xb2, 0xe4, 0x85, 0x34, 0x6d, 0x2e, 0x67,
	0x71, 0x4c, 0xa5, 0x34, 0xbd, 0xd8, 0x9d, 0x7a, 0xd1, 0x5d, 0x12, 0x6b, 0xd5, 0xc4, 0xfb, 0x1c,
	0x76, 0xbe, 0xa3, 0x19, 0x55, 0xf4, 0xdf, 0xae, 0x10, 0xde, 0x80, 0xb1, 0xc5, 0x1e, 0x27, 0xe7,
	0x8d, 0xd1, 0x23, 0x18, 0xd4, 0x2e, 0x26, 0x89, 0xbe, 0x82, 0x61, 0x7d, 0x1e, 0xf9, 0x0b, 0x1d,
	0xb9, 0x0b, 0xbd, 0xfe, 0x22, 0x18, 0xc8, 0x9a, 0x63, 0xf8, 0x13, 0x20, 0x3d, 0xcc, 0xdd, 0x48,
	0xf0, 0xdb, 0xe9, 0x99, 0xd5, 0x18, 0x6f, 0x2d, 0x37, 0xb3, 0x96, 0x66, 0x5b, 0xe3, 0x56, 0x5a,
	0x6b, 0xde, 0x4a, 0xe1, 0x16, 0x8c, 0xf5, 0xf2, 0x7a, 0x78, 0xf8, 0x77, 0xc2, 0x04, 0x46, 0x47,
	0xb4, 0xae, 0x59, 0x49, 0xee, 0x16, 0xb4, 0xb5, 0x59, 0xa2, 0x1b, 0xd0, 0x9e, 0xc9, 0xc5, 0x78,
	0xea, 0xbb, 0x6c, 0x8c, 0xaf, 0xb5, 0x84, 0xb7, 0x61, 0xf4, 0x9c, 0xa5, 0x9a, 0x4b, 0x7e, 0xb5,
	0x00, 0xba, 0x09, 0x51, 0xa4, 0x24, 0xea, 0xd4, 0xad, 0x59, 0xc9, 0x87, 0xbf, 0xb7, 0xa1, 0xfb,
	0x4a, 0xa3, 0x34, 0x2b, 0xef, 0x41, 0xc7, 0xb9, 0xa2, 0x5d, 0xb7, 0xf2, 0xf2, 0x52, 0xc1, 0xde,
	0xca, 0x9d, 0xf3, 0xbd, 0x7e, 0x86, 0xa1, 0x3b, 0xd0, 0x71, 0x29, 0x54, 0x9e, 0xcb, 0x29, 0x05,
	0xf5, 0x50, 0xd1, 0x17, 0xd0, 0xf3, 0x87, 0x20, 0xd1, 0x9e, 0xb3, 0x34, 0x8e, 0x25, 0x18, 0xd4,
	0x3c, 0x24, 0xba, 0x0f, 0xfd, 0xda, 0x63, 0x0a, 0x5d, 0x5e, 0xec, 0xd2, 0x78, 0x60, 0x05, 0xcd,
	0x97, 0x1a, 0x7a, 0x00, 0xc3, 0xfa, 0xf3, 0x4c, 0xa2, 0xa0, 0xb6, 0x63, 0xd3, 0x7b, 0xb3, 0xe1,
	0x2d, 0xd1, 0x23, 0x53, 0x9e, 0xfa, 0xd4, 0xbb, 0xba, 0xd8, 0x7c, 0xf5, 0x65, 0x19, 0x9c, 0x41,
	0x31, 0xf4, 0x04, 0x36, 0x1b, 0x0f, 0x54, 0x89, 0xae, 0xd5, 0xa2, 0x38, 0x63, 0x99, 0xed, 0xd5,
	0x65, 0x24, 0xfa, 0x16, 0x7a, 0x55, 0xe7, 0xa1, 0x4b, 0x0e, 0xd1, 0x7c, 0x3d, 0x06, 0x78, 0xd5,
	0xe0, 0x5a, 0xec, 0x10, 0x7a, 0x47, 0xd4, 0x71, 0xbb, 0x3a, 0xf8, 0x46, 0x6b, 0x05, 0xcb, 0x8f,
	0x1e, 0xf4, 0x18, 0x06, 0xf5, 0x76, 0x3d, 0xd7, 0xed, 0x8a, 0xd3, 0x9f, 0xd9, 0xdb, 0xf7, 0xa0,
	0x5f, 0xeb, 0xaa, 0xaa, 0x7c, 0xab, 0x9d, 0x16, 0x8c, 0x96, 0x96, 0x97, 0x27, 0x1b, 0x46, 0xfc,
	0xf2, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x39, 0x6f, 0x7a, 0x38, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QuestionClient is the client API for Question service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QuestionClient interface {
	Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*Users, error)
	GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*Campaign, error)
	ListCampaigns(ctx context.Context, in *ListCampaignRequest, opts ...grpc.CallOption) (*Campaigns, error)
	GetSupportRole(ctx context.Context, in *GetSupportRoleRequest, opts ...grpc.CallOption) (*SupportRole, error)
	ListSupportRoles(ctx context.Context, in *ListSupportRoleRequest, opts ...grpc.CallOption) (*SupportRoles, error)
	NewAnswer(ctx context.Context, in *NewAnswerRequest, opts ...grpc.CallOption) (*NewAnswerResponse, error)
	GetAnswer(ctx context.Context, in *AnswerIdRequest, opts ...grpc.CallOption) (*Answer, error)
	DeleteAnswer(ctx context.Context, in *AnswerIdRequest, opts ...grpc.CallOption) (*DeleteAnswerResponse, error)
	ListAnswers(ctx context.Context, in *ListAnswersRequest, opts ...grpc.CallOption) (*Answers, error)
}

type questionClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestionClient(cc grpc.ClientConnInterface) QuestionClient {
	return &questionClient{cc}
}

func (c *questionClient) Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.Question/Migrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.Question/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) ListUsers(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/proto.Question/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*Campaign, error) {
	out := new(Campaign)
	err := c.cc.Invoke(ctx, "/proto.Question/GetCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) ListCampaigns(ctx context.Context, in *ListCampaignRequest, opts ...grpc.CallOption) (*Campaigns, error) {
	out := new(Campaigns)
	err := c.cc.Invoke(ctx, "/proto.Question/ListCampaigns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetSupportRole(ctx context.Context, in *GetSupportRoleRequest, opts ...grpc.CallOption) (*SupportRole, error) {
	out := new(SupportRole)
	err := c.cc.Invoke(ctx, "/proto.Question/GetSupportRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) ListSupportRoles(ctx context.Context, in *ListSupportRoleRequest, opts ...grpc.CallOption) (*SupportRoles, error) {
	out := new(SupportRoles)
	err := c.cc.Invoke(ctx, "/proto.Question/ListSupportRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) NewAnswer(ctx context.Context, in *NewAnswerRequest, opts ...grpc.CallOption) (*NewAnswerResponse, error) {
	out := new(NewAnswerResponse)
	err := c.cc.Invoke(ctx, "/proto.Question/NewAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetAnswer(ctx context.Context, in *AnswerIdRequest, opts ...grpc.CallOption) (*Answer, error) {
	out := new(Answer)
	err := c.cc.Invoke(ctx, "/proto.Question/GetAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) DeleteAnswer(ctx context.Context, in *AnswerIdRequest, opts ...grpc.CallOption) (*DeleteAnswerResponse, error) {
	out := new(DeleteAnswerResponse)
	err := c.cc.Invoke(ctx, "/proto.Question/DeleteAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) ListAnswers(ctx context.Context, in *ListAnswersRequest, opts ...grpc.CallOption) (*Answers, error) {
	out := new(Answers)
	err := c.cc.Invoke(ctx, "/proto.Question/ListAnswers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionServer is the server API for Question service.
type QuestionServer interface {
	Migrate(context.Context, *MigrateRequest) (*empty.Empty, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	ListUsers(context.Context, *ListUserRequest) (*Users, error)
	GetCampaign(context.Context, *GetCampaignRequest) (*Campaign, error)
	ListCampaigns(context.Context, *ListCampaignRequest) (*Campaigns, error)
	GetSupportRole(context.Context, *GetSupportRoleRequest) (*SupportRole, error)
	ListSupportRoles(context.Context, *ListSupportRoleRequest) (*SupportRoles, error)
	NewAnswer(context.Context, *NewAnswerRequest) (*NewAnswerResponse, error)
	GetAnswer(context.Context, *AnswerIdRequest) (*Answer, error)
	DeleteAnswer(context.Context, *AnswerIdRequest) (*DeleteAnswerResponse, error)
	ListAnswers(context.Context, *ListAnswersRequest) (*Answers, error)
}

// UnimplementedQuestionServer can be embedded to have forward compatible implementations.
type UnimplementedQuestionServer struct {
}

func (*UnimplementedQuestionServer) Migrate(ctx context.Context, req *MigrateRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Migrate not implemented")
}
func (*UnimplementedQuestionServer) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedQuestionServer) ListUsers(ctx context.Context, req *ListUserRequest) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedQuestionServer) GetCampaign(ctx context.Context, req *GetCampaignRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaign not implemented")
}
func (*UnimplementedQuestionServer) ListCampaigns(ctx context.Context, req *ListCampaignRequest) (*Campaigns, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCampaigns not implemented")
}
func (*UnimplementedQuestionServer) GetSupportRole(ctx context.Context, req *GetSupportRoleRequest) (*SupportRole, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportRole not implemented")
}
func (*UnimplementedQuestionServer) ListSupportRoles(ctx context.Context, req *ListSupportRoleRequest) (*SupportRoles, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSupportRoles not implemented")
}
func (*UnimplementedQuestionServer) NewAnswer(ctx context.Context, req *NewAnswerRequest) (*NewAnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewAnswer not implemented")
}
func (*UnimplementedQuestionServer) GetAnswer(ctx context.Context, req *AnswerIdRequest) (*Answer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnswer not implemented")
}
func (*UnimplementedQuestionServer) DeleteAnswer(ctx context.Context, req *AnswerIdRequest) (*DeleteAnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAnswer not implemented")
}
func (*UnimplementedQuestionServer) ListAnswers(ctx context.Context, req *ListAnswersRequest) (*Answers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAnswers not implemented")
}

func RegisterQuestionServer(s *grpc.Server, srv QuestionServer) {
	s.RegisterService(&_Question_serviceDesc, srv)
}

func _Question_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/Migrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).Migrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).ListUsers(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/GetCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetCampaign(ctx, req.(*GetCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_ListCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).ListCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/ListCampaigns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).ListCampaigns(ctx, req.(*ListCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetSupportRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetSupportRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/GetSupportRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetSupportRole(ctx, req.(*GetSupportRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_ListSupportRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupportRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).ListSupportRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/ListSupportRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).ListSupportRoles(ctx, req.(*ListSupportRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_NewAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).NewAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/NewAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).NewAnswer(ctx, req.(*NewAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/GetAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetAnswer(ctx, req.(*AnswerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_DeleteAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).DeleteAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/DeleteAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).DeleteAnswer(ctx, req.(*AnswerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_ListAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).ListAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Question/ListAnswers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).ListAnswers(ctx, req.(*ListAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Question_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Question",
	HandlerType: (*QuestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Migrate",
			Handler:    _Question_Migrate_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Question_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Question_ListUsers_Handler,
		},
		{
			MethodName: "GetCampaign",
			Handler:    _Question_GetCampaign_Handler,
		},
		{
			MethodName: "ListCampaigns",
			Handler:    _Question_ListCampaigns_Handler,
		},
		{
			MethodName: "GetSupportRole",
			Handler:    _Question_GetSupportRole_Handler,
		},
		{
			MethodName: "ListSupportRoles",
			Handler:    _Question_ListSupportRoles_Handler,
		},
		{
			MethodName: "NewAnswer",
			Handler:    _Question_NewAnswer_Handler,
		},
		{
			MethodName: "GetAnswer",
			Handler:    _Question_GetAnswer_Handler,
		},
		{
			MethodName: "DeleteAnswer",
			Handler:    _Question_DeleteAnswer_Handler,
		},
		{
			MethodName: "ListAnswers",
			Handler:    _Question_ListAnswers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
